### ISSUE TITLE
smatch false positive warning for uninitialized symbol, when creating a block with "for()"

### ISSUE THREAD

**Issue by vcgomes** [error27/smatch#7]
When proposing some patches to overlayfs, I was notified that those changes were introducing new smatch warnings:

https://lore.kernel.org/all/202401281540.6nl399om-lkp@intel.com/

The warnings in the proposed patch are in places in which I use `scoped_guard()`, that uses a "special" 'for' to create a new block. And sorry for the confusing title, I don't know the correct name for that "for" idiom.

I could come up with the following reproducer:

```
#include <stdio.h>
#include <stdbool.h>

int main(void)
{
	int n;

	for (bool done = false; !done; done = true) {
		n = printf("did it!\n");
	}

	return n > 1 ? 0 : 1;
}

```

smatch gives: `repro.c:12 main() error: uninitialized symbol 'n'.`

It compiles without warnings with `gcc -Wextra -Wall -o repro repro.c`.

**Comment by error27** [comment]
That should be fixed in the current code.

7655150cf3f6 ("flow/conditions: fix ordering bug")

Also sorry that you received that email.  You're looking at the unfiltered emails.  They're sent to my error27@gmail.com address, and I look them over a resend the useful warnings.

**Comment by vcgomes** [comment]
I should have tried the most recent smatch tree, sorry about that. The simple reproducer warning is gone. 

I still see a warning on actual code, on the in progress series I am working on, I could be easily doing something wrong. But in case I am not, perhaps there are still issues with more complex conditions?

**Comment by error27** [comment]
Let me know the git tree and the warning message and I can take a look at it.

One issue is that Smatch needs a bit of help parsing all the new class_<lock type>_lock_ptr().  Every time someone writes a new one those functions then I have to add it into the the smatch_data/db/kernel.return_fixes file (the try_lock functions are fine and don't have to be added).

I just pushed a change which adds the class_device_lock_ptr().  So that might be the issue.  Or less likely if you were building a 32bit kernel then I just pushed a fix for those as well.  https://github.com/error27/smatch/commit/d786c0f07d9b583711e81ed62a981dc1df467408

The only remaining known issue is when you have a goto inside the scoped_guard().  I need to create a going_to_out_of_scope() so I can do something like "if (going_to_out_of_scope()) call_release_functions();".

**Comment by error27** [comment]
On Wed, Feb 21, 2024 at 03:41:17PM -0800, Vinicius Gomes wrote:
> Sorry for the delay. My tree is here:
> 
> https://github.com/vcgomes/net-next/tree/cred-override-light-v3
> 
> Still seeing
> ```
>  CHECK   fs/overlayfs/xattrs.c
> fs/overlayfs/export.c:815 ovl_fh_to_dentry() warn: variable dereferenced before IS_ERR check 'fh' (see line 805)

The IS_ERR_OR_NULL() check could be removed.

> fs/overlayfs/xattrs.c:49 ovl_xattr_set() error: uninitialized symbol 'err'.
> fs/overlayfs/xattrs.c:119 ovl_listxattr() error: uninitialized symbol 'res'.

Yeah.  The cred guard is new in that tree.  It hasn't hit linux-next,
yet.

Every time we add a new guard lock and it's not a lock which can fail
then I have to add an annotation to say it can't fail.  It's not 100%
ideal.  Basically, as soon as it hits linux-next then I see it and add
the lines to the smatch_data/db/kernel.return_fixes file.

regards,
dan carpenter

commit 9f427a02e9d5acf89a3ec6a66ddb4a32f08e0f1c
Author: Dan Carpenter ***@***.***>
Date:   Thu Feb 22 08:55:14 2024 +0300

    db/kernel.return_fixes: add cred scoped guard annotations
    
    There is a new scoped_guard(cred, ovl_creds(dentry->d_sb)) function which
    needs to be annotated.
    
    Signed-off-by: Dan Carpenter ***@***.***>

diff --git a/smatch_data/db/kernel.return_fixes b/smatch_data/db/kernel.return_fixes
index c216e5f020d9..8e934266f1bc 100644
--- a/smatch_data/db/kernel.return_fixes
+++ b/smatch_data/db/kernel.return_fixes
@@ -108,6 +108,8 @@ class_raw_spinlock_lock_ptr 0-u32max[$0->lock] 4096-ptr_max[$0->lock]
 class_rcu_lock_ptr 0-u32max[$0->lock] 4096-ptr_max[$0->lock]
 class_spinlock_lock_ptr 0-u32max[$0->lock] 4096-ptr_max[$0->lock]
 class_device_lock_ptr 0-u32max[*$0] 4096-ptr_max[*$0]
+class_cred_lock_ptr 0-u64max[$0->lock] 4096-ptr_max[$0->lock]
+class_cred_lock_ptr 0-u32max[$0->lock] 4096-ptr_max[$0->lock]
 platform_get_irq_byname 0-s32max 1-s32max
 __kthread_create_on_node 0-u64max 4096-ptr_max
 of_graph_get_endpoint_count 0-u32max 0-s32max

**Comment by vcgomes** [comment]
> On Wed, Feb 21, 2024 at 03:41:17PM -0800, Vinicius Gomes wrote: Sorry for the delay. My tree is here: https://github.com/vcgomes/net-next/tree/cred-override-light-v3 Still seeing ``` CHECK fs/overlayfs/xattrs.c fs/overlayfs/export.c:815 ovl_fh_to_dentry() warn: variable dereferenced before IS_ERR check 'fh' (see line 805)
> The IS_ERR_OR_NULL() check could be removed.

It's on a part of the code that I don't touch, will fix it separately.

> fs/overlayfs/xattrs.c:49 ovl_xattr_set() error: uninitialized symbol 'err'. fs/overlayfs/xattrs.c:119 ovl_listxattr() error: uninitialized symbol 'res'.
> Yeah. The cred guard is new in that tree. It hasn't hit linux-next, yet. Every time we add a new guard lock and it's not a lock which can fail then I have to add an annotation to say it can't fail. It's not 100% ideal. Basically, as soon as it hits linux-next then I see it and add the lines to the smatch_data/db/kernel.return_fixes file. regards, dan carpenter commit [9f427a0](https://github.com/error27/smatch/commit/9f427a02e9d5acf89a3ec6a66ddb4a32f08e0f1c) Author: Dan Carpenter ***@***.***> Date: Thu Feb 22 08:55:14 2024 +0300 db/kernel.return_fixes: add cred scoped guard annotations There is a new scoped_guard(cred, ovl_creds(dentry->d_sb)) function which needs to be annotated. Signed-off-by: Dan Carpenter ***@***.***> diff --git a/smatch_data/db/kernel.return_fixes b/smatch_data/db/kernel.return_fixes index c216e5f020d9..8e934266f1bc 100644 --- a/smatch_data/db/kernel.return_fixes +++ b/smatch_data/db/kernel.return_fixes @@ -108,6 +108,8 @@ class_raw_spinlock_lock_ptr 0-u32max[$0->lock] 4096-ptr_max[$0->lock] class_rcu_lock_ptr 0-u32max[$0->lock] 4096-ptr_max[$0->lock] class_spinlock_lock_ptr 0-u32max[$0->lock] 4096-ptr_max[$0->lock] class_device_lock_ptr 0-u32max[*$0] 4096-ptr_max[*$0] +class_cred_lock_ptr 0-u64max[$0->lock] 4096-ptr_max[$0->lock] +class_cred_lock_ptr 0-u32max[$0->lock] 4096-ptr_max[$0->lock] platform_get_irq_byname 0-s32max 1-s32max __kthread_create_on_node 0-u64max 4096-ptr_max of_graph_get_endpoint_count 0-u32max 0-s32max

Oh, I see. Didn't know that the checks are custom made for each guard.

I guess we can close this issue, or do you prefer to wait until what I am proposing is applied?

Thank you.

**Comment by error27** [comment]
I applied it.  Thanks!
